### ISSUE TITLE
ubuntu:22.04 old-version of mtools yields crash

### ISSUE THREAD

**Issue by vanillaSprinkles** [netbootxyz/docker-builder#48]
using the `ghcr.io/netbootxyz/builder:latest` image with the repo netboot.xyz; one of the makefiles uses a series of commands part of the `mtools` package; the installed version (4.0.32) results in a crash causing the build to fail.

The downstream build that fails is at (currently the HEAD of development branch): https://github.com/netbootxyz/netboot.xyz/blob/dabf12b5d82e155ee0bd79c9ed5a9bb70fd5c8dc/roles/netbootxyz/templates/pipxe/Makefile-rpi4.j2#L56

steps to reproduce:
( pre setup )
- within the docker image created  (or ubuntu:22.04); install mtools
  - if `ubuntu:22.04`
    - `apt update`
    - `apt install mtools`
  - if `ghcr.io/netbootxyz/builder:latest`
    - `apt install mtools`

- mtools specific commands (run interactive container, bash):
```bash
export MTOOLSRC=mtoolsrc

size_in_mb=32
file=sdcard2.img

cat <<EOF > ${MTOOLSRC}
drive z:
file="${file}"
partition=1
EOF

truncate -s ${size_in_mb}M ${file}
mpartition -I -c -b 32 -s 32 -h 64 -t ${size_in_mb} -a "z:"

mformat -v "piPXE" "z:"
```

copying in the 4.0.43 binaries on top of these installed by apt will result in a success when exec'ing the above code.
  ( To be frank im an arch fan and the ubuntu/debian apt-repo fun is not my specialty )

recommend use of the latest version of ubuntu - or maybe the experimental repo can be added and the mtools 4.0.43 package can be installed ?

**Comment by antonym** [comment]
Switched to 24.04 LTS now
